"""File containing constants."""
HEADER_TYPE = 'Content-Type'
HEADER_LENGTH = 'Content-Length'
JSON_TYPE = 'application/json'
OK = 200
NOT_FOUND = 404
BAD_REQUEST = 400
INTERNAL_SERVER_ERROR = 500
TIMEOUT = 30
CAL500 = 500.0
